const STOCK_GREEN = '#00ff00';
const STOCK_RED = '#ff0000';
const WHITE = '#FFFFFF';
const symbolToName = {'DJI': "DOW", 'IXIC': "NASDAQ", 'GSPC': "S&P 500"}
const STOCK_LIMITATION_FOR_REGULAR_USER = 5;
export {STOCK_GREEN, STOCK_RED, symbolToName, WHITE, STOCK_LIMITATION_FOR_REGULAR_USER}